# server port
server:
  port: 8080  # 원하는 포트로 변경
  address: 0.0.0.0

# database
spring:
  profiles:
    active: local  # 활성화할 프로필 설정

  config:
    import: application-secret.yaml  # secret 파일 불러오기

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/animal?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234

  mail:
    host: smtp.gmail.com
    port: 587
    username: mypetstory12@gmail.com
    password: fwfp tqik ziyi xmrf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kakao:
    api:
      url: https://kapi.kakao.com/v2/api/talk/memo/send
      token: YOUR_ACCESS_TOKEN

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: RA4A7xk3zhWx3czBZPCtZpbalul7W4uZ1p3NzTjAC9kFbHX3CmRtL7

# mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
  #MybatisAlias
  type-aliases-package: com.project.animal.dto

openai:
  api:
    url: https://api.openai.com/v1/chat/completions